import { Character } from "./types";

export const demoCharacters: Character[] = [
  {
    id: "demo-alor",
    name: "Alor",
    race: "Drow",
    className: "Fighter",
    subclass: "Battle Master",
    level: 5,
    role: "Tactical striker / control",
    heroicInspiration: true,
    initiative: 3,
    combat: {
      hp: 42,
      maxHp: 52,
      tempHp: 0,
      ac: 17,
      speed: 30,
      passivePerception: 14,
      passiveInvestigation: 10,
      passiveInsight: 11,
      conditions: [],
      exhaustion: 0,
    },
    stats: { str: 14, dex: 16, con: 14, int: 10, wis: 12, cha: 8 },
    resources: [
      {
        id: "r1",
        name: "Action Surge",
        current: 0,
        max: 1,
        recovery: "short-rest",
        source: "Class",
        description: "Take one additional action on your turn.",
      },
      {
        id: "r2",
        name: "Second Wind",
        current: 1,
        max: 2,
        recovery: "long-rest",
        source: "Class",
        description: "Bonus action to regain 1d10 + level HP.",
      },
      {
        id: "r3",
        name: "Superiority Dice",
        current: 3,
        max: 4,
        recovery: "short-rest",
        source: "Class",
        description: "Fuel Battle Master maneuvers that enhance an attack.",
      },
      {
        id: "r4",
        name: "Whisper of the Underdark Charges",
        current: 2,
        max: 3,
        recovery: "dawn",
        source: "Item",
      },
    ],
    spellSlots: [],
    knownSpells: [],
    features: [
      { id: "f1", name: "Fighting Style: Dueling", source: "Class", description: "+2 damage with a one-handed melee weapon and no other weapon in the other hand." },
      { id: "f2", name: "Extra Attack", source: "Class", description: "Attack twice, instead of once, whenever you take the Attack action." },
      { id: "f3", name: "Fey Ancestry", source: "Race", description: "Advantage on saving throws against being Charmed, and magic can't put you to sleep." },
      { id: "f4", name: "Darkvision", source: "Race", description: "See in dim light within 120 feet as if bright light, and in darkness as if dim light." },
    ],
    savingThrowProficiencies: ["str", "con"],
    skillProficiencies: [
      { name: "athletics", proficient: true, expertise: false },
      { name: "perception", proficient: true, expertise: false },
      { name: "intimidation", proficient: true, expertise: false },
    ],
    resistances: [],
    immunities: [],
    vulnerabilities: [],
    advantages: ["Advantage: Saving Throws — to avoid or end the Charmed condition (Fey Ancestry)"],
    senses: [{ name: "Darkvision", range: 120 }],
    inventory: [
      { id: "i1", name: "Longsword", rarity: "Common", category: "Weapon", quantity: 1 },
      { id: "i2", name: "Chain Mail", rarity: "Common", category: "Armor", quantity: 1 },
      {
        id: "i3",
        name: "Whisper of the Underdark",
        rarity: "Rare",
        category: "Magic Item",
        quantity: 1,
        description: "Intelligent longsword — grants advantage on Stealth checks in dim light or darkness.",
      },
      {
        id: "i4",
        name: "Potion of Healing",
        rarity: "Common",
        category: "Consumable",
        quantity: 2,
        description: "Regain 2d4 + 2 HP when you drink this potion.",
      },
    ],
    currency: { cp: 0, sp: 0, ep: 0, gp: 42, pp: 0 },
    notes:
      "A tactical character who works best through positioning and control. Wields the magic sword Whisper of the Underdark. Give him situations where his battlefield decisions carry real weight.",
  },
  {
    id: "demo-lilith",
    name: "Lilith",
    race: "Drow",
    className: "Paladin",
    subclass: "Oath of Lathander",
    level: 5,
    role: "Frontline support / divine burst",
    heroicInspiration: false,
    initiative: 1,
    combat: {
      hp: 39,
      maxHp: 47,
      tempHp: 0,
      ac: 18,
      speed: 30,
      passivePerception: 13,
      passiveInvestigation: 10,
      passiveInsight: 11,
      conditions: [],
      exhaustion: 0,
    },
    stats: { str: 16, dex: 12, con: 14, int: 10, wis: 13, cha: 16 },
    resources: [
      {
        id: "r1",
        name: "Lay on Hands",
        current: 15,
        max: 25,
        recovery: "long-rest",
        source: "Class",
        description: "Pool of HP to heal (touch) or 5 HP to cure a disease/poison.",
      },
      {
        id: "r2",
        name: "Channel Divinity",
        current: 1,
        max: 1,
        recovery: "long-rest",
        source: "Class",
        description: "Fuel your Sacred Oath's Channel Divinity options.",
      },
      { id: "r3", name: "Heroic Inspiration", current: 0, max: 1, recovery: "manual" },
    ],
    spellSlots: [
      { level: 1, current: 2, max: 4 },
      { level: 2, current: 1, max: 2 },
    ],
    spellcasting: { modifier: 3, attack: 6, saveDc: 14 },
    knownSpells: [
      { id: "s1", name: "Bless", level: 1, school: "Enchantment", source: "Class", description: "Up to three creatures you choose add 1d4 to attack rolls and saving throws." },
      { id: "s2", name: "Cure Wounds", level: 1, school: "Evocation", source: "Class", description: "A creature you touch regains 1d8 + your spellcasting modifier HP." },
      { id: "s3", name: "Find Steed", level: 2, school: "Conjuration", source: "Class", description: "Summon a spirit that assumes the form of a loyal mount." },
      { id: "s4", name: "Zone of Truth", level: 2, school: "Enchantment", source: "Class", description: "Creatures in the zone can't speak deliberate lies while inside." },
    ],
    features: [
      { id: "f1", name: "Divine Smite", source: "Class", description: "Expend a spell slot to deal extra radiant damage on a melee weapon hit." },
      { id: "f2", name: "Lay on Hands", source: "Class", description: "A pool of healing power you can draw from to restore HP or cure ailments." },
      { id: "f3", name: "Radiant Strikes", source: "Subclass", description: "Your weapon attacks deal extra radiant damage." },
      { id: "f4", name: "Fey Ancestry", source: "Race", description: "Advantage on saving throws against being Charmed, and magic can't put you to sleep." },
    ],
    savingThrowProficiencies: ["wis", "cha"],
    skillProficiencies: [
      { name: "athletics", proficient: true, expertise: false },
      { name: "persuasion", proficient: true, expertise: false },
      { name: "religion", proficient: true, expertise: false },
    ],
    resistances: [],
    immunities: [],
    vulnerabilities: [],
    advantages: ["Advantage: Saving Throws — to avoid or end the Charmed condition (Fey Ancestry)"],
    senses: [{ name: "Darkvision", range: 120 }],
    inventory: [
      { id: "i1", name: "Longsword", rarity: "Common", category: "Weapon", quantity: 1 },
      { id: "i2", name: "Plate Armor", rarity: "Common", category: "Armor", quantity: 1 },
      {
        id: "i3",
        name: "Holy Symbol of Lathander",
        rarity: "Uncommon",
        category: "Magic Item",
        quantity: 1,
      },
      {
        id: "i4",
        name: "Potion of Healing",
        rarity: "Common",
        category: "Consumable",
        quantity: 1,
        description: "Regain 2d4 + 2 HP when you drink this potion.",
      },
    ],
    currency: { cp: 0, sp: 0, ep: 0, gp: 118, pp: 2 },
    notes:
      "A strong bond with Lathander, a theme of light versus darkness. Scenes of moral choice, protecting the weak, or standing against dark forces work well for her.",
  },
];
